### PR TITLE
Add screenshots and description

### PR DESCRIPTION
**Pull request by oupson**
Fix https://github.com/oupson/jxlviewer/issues/7

### CODE REVIEW

**Comment by oupson** [comment]
@IzzySoft can you look if you have the time ? Thanks in advance !

**Comment by IzzySoft** [comment]
Thanks! That looks very good so far. A few remarks though:

* changelogs: I see you still use `versionCode:1` despite of already having multiple releases. As `versionCode` is what Android uses internally to tell versions apart, it **must be increased** with each release. Best place for that [would be here](https://github.com/oupson/jxlviewer/blob/main/app/build.gradle#L14).
* while your `full_description.txt` will format fine with the WebIf of my repo (perfect Markdown) we recently discovered that some Android clients (including the official one) will convert each new line to a `<br>` and thus space the description quite a lot (culprit for that is, as far as I understood, a library responsible for displaying the text; some alternatives are discussed for quite a while already but have not been implemented yet).  
Another developer found a nice work-around for that which I also already added to [my wiki](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane): they use [a perl script](https://github.com/tateisu/SubwayTooter/blob/main/fastlane/metadata/android/en-US/full_description.pl) with the full description embedded as HTML. When run, it creates a `full_description.txt` with the entire HTML put into one line, thus avoiding those "extra `<br>`. This works fine with any F-Droid repo. Not strictly needed, but I thought I mention that option – especially as you involve a CI job anyway already :wink:

That said: Just merge as-is, it's fine – but make sure to take care for the first bullet-point soon, and **optionally** consider the second.

**Comment by oupson** [comment]
> changelogs: I see you still use versionCode:1 despite of already having multiple releases.

I intend to release a new version with version code increase really soon (a 0.2.1 with a few bug fix). Is this a problem if 0.1.0 and 0.2.0 still share the same versionCode ?

Anyway thanks for taking the time to review !

**Comment by IzzySoft** [comment]
Well, what's past is past. Who had installed the first version will not update to the second if there's a third one – and who'd installed the second will be fine then anyway, right? So if you start increasing now, that should suffice I'd say.

And gladly done – looking forward to adding your app to my repo :smiley:

**Comment by IzzySoft** [comment]
Yeeha! Ready for the party then? In about 23 hours from now, it will [start here](https://apt.izzysoft.de/fdroid/index/apk/fr.oupson.jxlviewer) :smiley:

**Comment by oupson** [comment]
I will try to release the 0.2.1 as soon as possible.

It's going to be so cool to have the app on your repository !

**Comment by IzzySoft** [comment]
> It's going to be so cool to have the app on your repository !

Soon will be! And be welcome [picking a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme once the app shows up in my repo :smiley:

**Comment by IzzySoft** [comment]
PS, here's what to expect:
image

**Pull request merged**
